#pragma once

#include "Character_Meta.h"
#include "Map_Meta.h"
#include "Skill_Info.h"
#include "Item_Meta.h"

#include <Windows.h>

#include "nlohmann/json.hpp"

namespace Client
{
	static constexpr unsigned int		g_iWinSizeX = { 1280 };
	static constexpr unsigned int		g_iWinSizeY = { 720 };

	static constexpr float fDefaultFontSize = (1.f + (static_cast<float>(g_iWinSizeY) / 720.f - 1.f) * 0.7f) * 0.6f;

	enum class LEVEL { STATIC, LOADING, LOGO, LOBBY, GAMEPLAY, ENDING, END_DECO };

	enum class UILAYER { INGMAE, BACKGROUND, DECO_LAYER1, DECO_LAYER2, DECO_LAYER3, PANEL, PANEL_DECO, SLOT_PANEL, SLOT, SLOT_DECO, BUTTON_IMAGE, BUTTON, BUTTON_IMAGE_OVER, PANEL_OVER, PANEL_DECO_OVER, PANEL_SLOT_OVER, BG_END, END_DECO, END};

	enum class STAGE { LOBBY, SELECT, STAGE_END };

	enum class ANIMMESH_SHADER { DEFAULT, SHADOW, OUTLINE};
	enum class MESH_SHADER { DEFAULT, NORMALMAP, WATER, SHADOW, OUTLINE, OUTLINE_NO_DEPTH_TEST, STENCILWRITE, NORMALMAPSTENCILWRITE};
	enum class EFFECT_SHADER { DEFAULT, ALPHABLEND };
	enum class MESHEFFECT_SHADER { DEFAULT, ALPHABLEND, BLEND, Q_SPIN, Q_DRAGON, WIND, CONVERT_ALPHA, COLOR_ADD };

	enum class Collision_Layer
	{
		PLAYER = 1 << 0,
		MONSTER = 1 << 1,
		ITEMBOX = 1 << 2,
		ITEMBOX_COLLECTIBLE = 1 << 3,
		SKILL = 1 << 4,
		ENEMY_SKILL = 1 << 5,
		ENEMY = 1 << 6,
		GROUND = 1 << 7,
	};

	enum class SOUND_KEY {
		BGM_LOBBY, BGM_SELECT, LOBBY_TAB_HOVER, LOBBY_TAB_CLICK, CHAR_HOVER, CHAR_CLICK, SELECT_CLICK, GAMESTART_CLICK,
		LIDAILIN_SELECT, HYUNWOO_SELECT,
		LIDAILIN_NORMAL_ATK, LIDAILIN_NORMAL_ATK_P, LIDAILIN_NORMAL_ATK_WIND_1, LIDAILIN_NORMAL_ATK_WIND_2, LIDAILIN_Q1, LIDAILIN_Q2, LIDAILIN_Q3, LIDAILIN_Q_HIT, LIDAILIN_W, LIDAILIN_W_VOICE_1, LIDAILIN_W_VOICE_2, LIDAILIN_W_VOICE_3, LIDAILIN_E, LIDAILIN_E_P, LIDAILIN_E_VOICE, LIDAILIN_E_HIT, LIDAILIN_R_DASH, LIDAILIN_R_HIT,
		BGM_ALLEY, BGM_ARCHERY, BGM_CEMETERY, BGM_CHURCH, BGM_DOWNTOWN, BGM_FACTORY, BGM_FOREST, BGM_HARBOR, BGM_HOSPITAL, BGM_HOTEL, BGM_LABORATORY, BGM_POND, BGM_SANDY_BEACH, BGM_SCHOOL, BGM_TEMPLE, BGM_UPTOWN,
		BAT_ATTACK, BAT_DIE, BAT_HIT,
		BEAR_ATTACK1, BEAR_ATTACK2, BEAR_DIE, BEAR_HIT, BEAR_WAKEUP,
		BOAR_ATTACK, BOAR_DIE, BOAR_HIT,
		CHICKEN_ATTACK, CHICKEN_DIE, CHICKEN_HIT, CHICKEN_WAKEUP,
		WILDDOG_ATTACK, WILDDOG_DIE, WILDDOG_HIT, WILDDOG_WAKEUP,
		WOLF_ATTACK, WOLF_DIE, WOLF_HIT, WOLF_WAKEUP,
		DAY_BIRD1, DAY_BIRD2, DAY_BIRD3, DAY_BIRD4, DAY_BIRD5, DAY_BIRD6, NIGHT_BIRD1, NIGHT_BIRD2, NIGHT_BIRD3, NIGHT_BIRD4, NIGHT_BIRD5, SUNNY,
		COLLECT, COLLECT_BRANCH, COLLECT_STONE, CRAFT_FOOD, CRAFT_TOOL,
		LIDAILIN_COLLECTBRANCH_VOICE, LIDAILIN_COLLECTFLOWER_VOICE, LIDAILIN_COLLECTSTONE_VOICE,
		LIDAILIN_CRAFTEPIC_1_VOICE, LIDAILIN_CRAFTEPIC_2_VOICE, LIDAILIN_CRAFTRARE_3_VOICE, LIDAILIN_CRAFTUNCOMMON_1_VOICE, LIDAILIN_CRAFTUNCOMMON_2_VOICE, LIDAILIN_CRAFTUNCOMMON_3_VOICE, LIDAILIN_CRAFTLEGENDARY_2_VOICE,
		LIDAILIN_MAKEFOOD_1_VOICE, LIDAILIN_MAKEFOOD_3_VOICE,
		ITEM_PICKUP, ITEM_FAIL, EQUIP_ITEM,
		EFFECT_LEVELUP, SKILL_UP,
		CONSUME_EAT_3,
		FOOTSTEPASPHALT_W1, FOOTSTEPASPHALT_W2, FOOTSTEPASPHALT_W3, FOOTSTEPASPHALT_W4,

		RESULT_VICTORY,

		// Fiora
		ATTACKRAPIER_R2,
		FIORA_SKILL01_ATTACK, FIORA_SKILL01_HIT_R2,
		FIORA_SKILL02_ATTACK_1, FIORA_SKILL02_ATTACK_2,
		FIORA_SKILL03_MOVE, FIORA_SKILL03_HIT,
		FIORA_SKILL04_ATTACK01, FIORA_SKILL04_ATTACK01_HIT, FIORA_SKILL04_ATTACK02, FIORA_SKILL04_ATTACK02_HIT,

		// OpenSound
		OPENSOUND_ALTARTABLE_01, OPENSOUND_ATM_01, OPENSOUND_BAG_01,
		OPENSOUND_BARBEQUEGRILL_01, OPENSOUND_BEACHCHAIR_01, OPENSOUND_BIOTOILET_01,
		OPENSOUND_BOAT_01, OPENSOUND_BOX_01, OPENSOUND_BOX_02,
		OPENSOUND_CARTONBOX_01, OPENSOUND_CEMENTMIXER, OPENSOUND_COFFEEMACHINE_01,
		OPENSOUND_COFFIN_01, OPENSOUND_CONCRETEBAG_SET_01, OPENSOUND_CONFESSIONAL_01,
		OPENSOUND_DRUM_01, OPENSOUND_DUMPSTER_01, OPENSOUND_ERASERCLEANER_01,
		OPENSOUND_FILINGCABINETS_01, OPENSOUND_GARBAGEBAG_SET_01, OPENSOUND_HOSPITAL_CABINET_01,
		OPENSOUND_HOSPITAL_CART_01, OPENSOUND_ICEBOX_01, OPENSOUND_JAR_01,
		OPENSOUND_JAR_BIG_01, OPENSOUND_LOCKER_01,
		OPENSOUND_ORGAN_01, OPENSOUND_PALLET_LOADED_01, OPENSOUND_SEDAN_BROWN_01,
		OPENSOUND_SEDAN_POLICE_01, OPENSOUND_SEDAN_TAXI_01, OPENSOUND_STEELBOX_02,
		OPENSOUND_STEELBOX_03, OPENSOUND_SUITCASE_01, OPENSOUND_SWITCHBOARD_01,
		OPENSOUND_TEMPLE_BOX_01, OPENSOUND_THURIBLE_01, OPENSOUND_TOMB_01,
		OPENSOUND_TRASHCAN_01, OPENSOUND_TRASHCAN2_01, OPENSOUND_TREESTUMP_01,
		OPENSOUND_TREESTUMP_02, OPENSOUND_UPTOWN_BOOKCASE_01, OPENSOUND_UPTOWN_DRAWER_01,
		OPENSOUND_UPTOWN_FIREPLACE_01, OPENSOUND_VENDINGMACHINE_01, OPENSOUND_WATERTANK_01,
		OPENSOUND_WHEELBARROW_01, OPENSOUND_WRECKCAR_01,
		DEAD_OPEN,

		// Move Area
		LIDAILIN_MOVEINALLEY_1,			LIDAILIN_MOVEINALLEY_2,			LIDAILIN_MOVEINALLEY_3,
		LIDAILIN_MOVEINARCHERY_1,		LIDAILIN_MOVEINARCHERY_2,		LIDAILIN_MOVEINARCHERY_3,
		LIDAILIN_MOVEINCEMETERY_1,		LIDAILIN_MOVEINCEMETERY_2,		LIDAILIN_MOVEINCEMETERY_3,
		LIDAILIN_MOVEINCHURCH_1,		LIDAILIN_MOVEINCHURCH_2,		LIDAILIN_MOVEINCHURCH_3,
		LIDAILIN_MOVEINFACTORY_1,		LIDAILIN_MOVEINFACTORY_2,		LIDAILIN_MOVEINFACTORY_3,
		LIDAILIN_MOVEINFIRESTATION_1,   LIDAILIN_MOVEINFIRESTATION_2,   LIDAILIN_MOVEINFIRESTATION_3,
		LIDAILIN_MOVEINFOREST_1,		LIDAILIN_MOVEINFOREST_2,		LIDAILIN_MOVEINFOREST_3,
		LIDAILIN_MOVEINGASSTATION_1,	LIDAILIN_MOVEINGASSTATION_2,	LIDAILIN_MOVEINGASSTATION_3,
		LIDAILIN_MOVEINHARBOR_1,		LIDAILIN_MOVEINHARBOR_2,		LIDAILIN_MOVEINHARBOR_3,
		LIDAILIN_MOVEINHOSPITAL_1,		LIDAILIN_MOVEINHOSPITAL_2,		LIDAILIN_MOVEINHOSPITAL_3,
		LIDAILIN_MOVEINHOTEL_1,			LIDAILIN_MOVEINHOTEL_2,			LIDAILIN_MOVEINHOTEL_3,
		LIDAILIN_MOVEINLABORATORY_1,	LIDAILIN_MOVEINLABORATORY_2,	LIDAILIN_MOVEINLABORATORY_3,
		LIDAILIN_MOVEINPOLICESTATION_1, LIDAILIN_MOVEINPOLICESTATION_2, LIDAILIN_MOVEINPOLICESTATION_3,
		LIDAILIN_MOVEINPOND_1,			LIDAILIN_MOVEINPOND_2,			LIDAILIN_MOVEINPOND_3,
		LIDAILIN_MOVEINSANDYBEACH_1,	LIDAILIN_MOVEINSANDYBEACH_2,	LIDAILIN_MOVEINSANDYBEACH_3,
		LIDAILIN_MOVEINSCHOOL_1,		LIDAILIN_MOVEINSCHOOL_2,		LIDAILIN_MOVEINSCHOOL_3,
		LIDAILIN_MOVEINSTREAM_1,		LIDAILIN_MOVEINSTREAM_2,		LIDAILIN_MOVEINSTREAM_3,
		LIDAILIN_MOVEINTEMPLE_1,		LIDAILIN_MOVEINTEMPLE_2,		LIDAILIN_MOVEINTEMPLE_3,
		LIDAILIN_MOVEINWAREHOUSE_1,		LIDAILIN_MOVEINWAREHOUSE_2,		LIDAILIN_MOVEINWAREHOUSE_3,
		LIDAILIN_MOVEINUPTOWN_1,		LIDAILIN_MOVEINUPTOWN_2,		LIDAILIN_MOVEINUPTOWN_3,
	};
	enum class SOUND_CHANNEL_LOBBY { BGM, SKIN_SELECT, FIXED_EFFECT1 };
	enum class SOUND_CHANNEL_GAMEPLAY { BGM, ENVIRONMENT_1, ENVIRONMENT_2, FIXED_EFFECT1, ACTION, VOICE };

	static constexpr float		fColliderCenterY = { 0.5f };

	struct INVENTORY_SLOT
	{
		int iItemId{ -1 };
		unsigned int iItemCnt{};
	};

	struct EQUIPMENT_SLOT
	{
		int iItemId{ -1 };
		ITEM_TYPE eItemType{};
	};

	struct DAMAGE_INFO
	{
		class CUnit* pUnit{};
		int iDamage{};
		bool bStun{};
		float fStunTime{};
	};
}


// 이 변수가 다른 곳에 정의되어 있다고 선언만 한다.
// 링크 단계에서 실제 정의(주소)와 연결된다.(이 헤더파일 포함하면 사용 가능)
extern HINSTANCE g_hInstance;
extern HWND g_hWnd;

// Client namespace를 만든 적이 없어서 위에서 반드시 만들어줘야 에러 안 뜸.
// 이거 해주면 매번 cpp에서 namespace 안 붙여도 됨.
using namespace Client;
